[features]
seeds = false
[programs.devnet]
certmachine1 = "32wMorHUnU6UhFbkzzNM6Npg2ztQGHsjuDnMYRrn8Dc2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/potato/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
